### ISSUE TITLE
Idea wanted

### ISSUE THREAD

**Issue by iceice666** [iceice666/resourcepack-server#1]
If you have some new idea, welcome to open a issue to tell us.

**Comment by KiwiFlavoredApollo** [comment]
I like the idea of hosting resource pack server myself. It would be awesome if data packs and resource packs in my server could be automatically grouped together and be sent to clients. In that way I wouldn't need to tell them to download resource packs by themselves.

**Comment by iceice666** [comment]
> I like the idea of hosting resource pack server myself. It would be awesome if data packs and resource packs in my server could be automatically grouped together and be sent to clients. In that way I wouldn't need to tell them to download resource packs by themselves.

In Minecraft, datapack will only affect on server side.
[Datapack](https://minecraft.fandom.com/wiki/Data_pack) added some recipes, functions, achievement, etc... on server side.
It should not be send to client.

If u want to force player download resourcepack, see the [`require-resource-pack`](https://minecraft.fandom.com/wiki/Server.properties#:~:text=has%20no%20effect.-,require%2Dresource%2Dpack,-boolean) option.

And just a reminder, you have to set [`resource-pack`](https://minecraft.fandom.com/wiki/Server.properties#:~:text=RCON%20network%20port.-,resource%2Dpack,-string) this option to `<your-server-ip>:<resourcepack-server-port>` (e.g. `123.45.678.90:25566`)

**Comment by KiwiFlavoredApollo** [comment]
I should have made myself clear on that some data packs listed on Modrinth are also claimed to be resource packs and optionally needed to be installed on client too. That's the reason why I used the term "data pack". But I get your point. 

As a server admin, it's always frustrating to tell people who want to join my server to download multiple resource packs in order to maximize their experience on my server. On the other hand, only single resource pack can be hosted. Seems like modpack is the only viable option for this case.

**Comment by iceice666** [comment]
> I should have made myself clear on that some data packs listed on Modrinth are also claimed to be resource packs and optionally needed to be installed on client too. That's the reason why I used the term "data pack". But I get your point.
> 
> As a server admin, it's always frustrating to tell people who want to join my server to download multiple resource packs in order to maximize their experience on my server. On the other hand, only single resource pack can be hosted. Seems like modpack is the only viable option for this case.

I understand your challenge, but Minecraft servers typically only support hosting a single resource pack. If you're looking to combine multiple resource packs for a more unified experience, you might have to mix them manually or use resources pack mixer.

[Gpt's answer about resources pack mixer](https://chat.openai.com/share/dbf40e44-553a-4d9a-b34b-0aa6bad597d8)

**Comment by Cynthia7979** [comment]
I was able to run this mod on fabric 1.19.2 (after manually editing `fabric.mod.json`), so expanding the mod's supported version range would be a good idea for more people to use it.
