### ISSUE TITLE
[Question] Quilt compatibility

### ISSUE THREAD

**Issue by Hexality** [iceice666/resourcepack-server#11]
How hard would it be to enable support for quilt? Allowing fabric mods to run on quilt used to be plug and play, I don't know if its still easy and feasible. It would be interesting if this could also be used with Quilt.

**Comment by iceice666** [comment]
according to [Quilt's faq](https://quiltmc.org/en/about/faq/):
> Which parts of Fabric is Quilt forking?
>
>All of them. Quilt is a hard fork of Fabric, and we aim to fork and maintain all projects necessary to exist independently of it.

And

>Can Quilt load Fabric mods?
>
>In most cases, yes. As Quilt is a fork, most Fabric mods should be compatible with Quilt. As long as maintaining Fabric compatibility doesn’t negatively impact the project, we’ll keep doing it — but if it does get to the point where maintaining it is no longer feasible, we’ll help move it to a community-run project and provide its developers with the support they need to keep working on it.
>
>It’s also worth noting that — as of this writing — Fabric mods that contain mixin plugins are supported, but this will change in the future. This isn’t a major issue as the vast majority of mods don’t use mixin plugins, but we’ll be happy to work with mod developers that need an alternative approach for Quilt.

I don't heard any about Quilt changed mixin-related API so far.
(and their docs still incomplete 😢😢😢)
So basically, Quilt is fully compatible with Fabric.

**Comment by Hexality** [comment]
I mean, trying to run your mod on Quilt is failing for me as its requesting a specific version of fabricloader that quilt fails to deliver, that's the main reason I asked.

**Comment by iceice666** [comment]
1) Please use the issue template to report a bug with the necessary information.
2) Quilt version is not planned. As I mentioned before, their documentation is still incomplete.
3) You're unable to start the game because the current Quilt loader only supports up to Fabric 0.16.4. You'll need to wait for the next Quilt version release or fallback to Fabric.
