### ISSUE TITLE
Server not prompting client to download

### ISSUE THREAD

**Issue by slidedrum** [iceice666/resourcepack-server#3]
I believe I have the mod correctly configured, because when I navigate to my server-ip in chrome, with the port 25566, I download the correct resource pack.  And I have resource-pack set up in my server.properties file as well.  When I set the download URL to something like dropbox, it works as expected.  Am I doing something wrong here?  This mod would be very convenient for me and my server.

**Comment by iceice666** [comment]
what the output of `/rps info` this command?

**Comment by GirafeGood** [comment]
I am experiencing the same issue
executing /rps info shows:
Current path: (nameofthepack).zip
SHA1:(the sha1 hash)

**Comment by iceice666** [comment]
Have you located a file with a name matching the SHA-1 hash in the `<your Minecraft root folder>/server-resource-packs` (client side)directory?   
If you have, could you please delete that file and then join the server again to verify if the server still doesn't prompt the client to download anything?

**Comment by dustindmiller** [comment]
I'm having a similar issue where when I update the resource pack and SHA1, clients don't recognize the update and use the old version of the resource pack. I'm unsure if it's the client or the server config, but it holds onto the last resource pack SHA1 file even after I delete and rejoin. It seems to use the latest version of the resource pack after I delete the file, but the SHA1 file stays the same no matter what I do.

**Comment by iceice666** [comment]
OK it seems that the sha1 value does not update after update the resourcepack.
I will try another implementation.
